Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 135

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 7
